#!/bin/sh

echo "==============Begin To Setup Game Server==============="
bundle install
rake setup
./rebar get-deps
./rebar compile
./start_on_daemon
echo "==============Finished To Setup Game Server==============="
