#!/usr/bin/env ruby

# This script is invoked on first push.
# You can do some initialize in this file.

puts "#{File.expand_path("./")}"
puts "#{File.expand_path("../install.sh")}"
`/bin/sh ../install.sh`