%%%===================================================================
%%% Generated by generate_api.rb 2014-02-28 21:44:05 +0800
%%%===================================================================
-module(api_decoder).
-export([decode/1]).
-include("include/protocol.hrl").

decode(<<0:?SHORT, Bin0/binary>>) ->
    {Name, Bin1} = utils_protocol:decode_string(Bin0),
    {PositionX, Bin2} = utils_protocol:decode_integer(Bin1),
    {PositionY, Bin3} = utils_protocol:decode_integer(Bin2),
    {UserId, Bin4} = utils_protocol:decode_string(Bin3),
    {[{name, Name}, {position_x, PositionX}, {position_y, PositionY}, {user_id, UserId}], Bin4};
decode(<<1:?SHORT, Bin0/binary>>) ->
    {Name, Bin1} = utils_protocol:decode_string(Bin0),
    {Position, Bin2} = utils_protocol:decode_integer(Bin1),
    {[{name, Name}, {position, Position}], Bin2};
decode(<<2:?SHORT, Bin0/binary>>) ->
    {Uuid, Bin1} = utils_protocol:decode_string(Bin0),
    {Udid, Bin2} = utils_protocol:decode_string(Bin1),
    {Name, Bin3} = utils_protocol:decode_string(Bin2),
    {Gem, Bin4} = utils_protocol:decode_integer(Bin3),
    {Paid, Bin5} = utils_protocol:decode_float(Bin4),
    {Building, Bin6} = api_decoder:decode(Bin5),
    {Towns, Bin7} = utils_protocol:decode_array(Bin6, fun(Data) -> api_decoder:decode(Data) end),
    {Team, Bin8} = utils_protocol:decode_array(Bin7, fun(Data) -> utils_protocol:decode_integer(Data) end),
    {[{uuid, Uuid}, {udid, Udid}, {name, Name}, {gem, Gem}, {paid, Paid}, {building, Building}, {towns, Towns}, {team, Team}], Bin8};
decode(<<3:?SHORT, Bin0/binary>>) ->
    {Udid, Bin1} = utils_protocol:decode_string(Bin0),
    {[{udid, Udid}], Bin1};
decode(<<4:?SHORT, Bin0/binary>>) ->
    {UserId, Bin1} = utils_protocol:decode_string(Bin0),
    {[{user_id, UserId}], Bin1}.
