%%%===================================================================
%%% Generated by generate_api.rb 2014-03-10 17:56:05 +0800
%%%===================================================================
-module(api_protocol).
-export([protocol_id/1, protocol_name/1]).

-define(NAME_MAPPED, [{success, 0},
                      {error, 1},
                      {town, 2},
                      {building, 3},
                      {user, 4},
                      {hero, 5},
                      {heros_info, 6},
                      {formation, 7},
                      {login_params, 8},
                      {public_info_params, 9},
                      {hero_info_params, 10},
                      {heros_info_params, 11},
                      {formation_info_params, 12},
                      {formation_update_params, 13}]).

-define(ID_MAPPED, [{0, success},
                    {1, error},
                    {2, town},
                    {3, building},
                    {4, user},
                    {5, hero},
                    {6, heros_info},
                    {7, formation},
                    {8, login_params},
                    {9, public_info_params},
                    {10, hero_info_params},
                    {11, heros_info_params},
                    {12, formation_info_params},
                    {13, formation_update_params}]).

protocol_id(Name) -> 
    proplists:get_value(Name, ?NAME_MAPPED).

protocol_name(Id) -> 
    proplists:get_value(Id, ?ID_MAPPED).
