%%%===================================================================
%%% Generated by generate_api.rb 2014-03-10 17:56:05 +0800
%%%===================================================================
-module(api_encoder).
-export([encode/2, encode_protocol/2]).

encode(ProtocolName, Value) ->
    ProtocolId = api_protocol:protocol_id(ProtocolName),
    EncodedValue = encode_protocol(ProtocolName, Value),
    list_to_binary([utils_protocol:encode_short(ProtocolId), EncodedValue]).
encode_protocol(success, Value) ->
    {Code} = Value,
    DataList = [
    utils_protocol:encode_integer(Code)
    ],
    list_to_binary(DataList);
encode_protocol(error, Value) ->
    {Code, Desc} = Value,
    DataList = [
    utils_protocol:encode_integer(Code),
        utils_protocol:encode_string(Desc)
    ],
    list_to_binary(DataList);
encode_protocol(town, Value) ->
    {Name, PositionX, PositionY, UserId} = Value,
    DataList = [
    utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(PositionX),
        utils_protocol:encode_integer(PositionY),
        utils_protocol:encode_string(UserId)
    ],
    list_to_binary(DataList);
encode_protocol(building, Value) ->
    {Name, Position} = Value,
    DataList = [
    utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(Position)
    ],
    list_to_binary(DataList);
encode_protocol(user, Value) ->
    {Uuid, Udid, Name, Gem, Paid, Building, Towns, Team} = Value,
    DataList = [
    utils_protocol:encode_string(Uuid),
        utils_protocol:encode_string(Udid),
        utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(Gem),
        utils_protocol:encode_float(Paid),
        encode_protocol(building, Building),
        utils_protocol:encode_array(Towns, fun(Item) -> api_encoder:encode_protocol(town, Item) end),
        utils_protocol:encode_array(Team, fun(Item) -> utils_protocol:encode_integer(Item) end)
    ],
    list_to_binary(DataList);
encode_protocol(hero, Value) ->
    {Uuid, UserId, Level, ConfigId} = Value,
    DataList = [
    utils_protocol:encode_string(Uuid),
        utils_protocol:encode_string(UserId),
        utils_protocol:encode_integer(Level),
        utils_protocol:encode_integer(ConfigId)
    ],
    list_to_binary(DataList);
encode_protocol(heros_info, Value) ->
    {Heros} = Value,
    DataList = [
    utils_protocol:encode_array(Heros, fun(Item) -> api_encoder:encode_protocol(hero, Item) end)
    ],
    list_to_binary(DataList);
encode_protocol(formation, Value) ->
    {Uuid, UserId, Matrix} = Value,
    DataList = [
    utils_protocol:encode_string(Uuid),
        utils_protocol:encode_string(UserId),
        utils_protocol:encode_array(Matrix, fun(Item) -> utils_protocol:encode_string(Item) end)
    ],
    list_to_binary(DataList);
encode_protocol(login_params, Value) ->
    {Udid} = Value,
    DataList = [
    utils_protocol:encode_string(Udid)
    ],
    list_to_binary(DataList);
encode_protocol(public_info_params, Value) ->
    {UserId} = Value,
    DataList = [
    utils_protocol:encode_string(UserId)
    ],
    list_to_binary(DataList);
encode_protocol(hero_info_params, Value) ->
    {Id} = Value,
    DataList = [
    utils_protocol:encode_string(Id)
    ],
    list_to_binary(DataList);
encode_protocol(heros_info_params, Value) ->
    {UserId} = Value,
    DataList = [
    utils_protocol:encode_string(UserId)
    ],
    list_to_binary(DataList);
encode_protocol(formation_info_params, Value) ->
    {UserId} = Value,
    DataList = [
    utils_protocol:encode_string(UserId)
    ],
    list_to_binary(DataList);
encode_protocol(formation_update_params, Value) ->
    {UserId, Matrix} = Value,
    DataList = [
    utils_protocol:encode_string(UserId),
        utils_protocol:encode_array(Matrix, fun(Item) -> utils_protocol:encode_string(Item) end)
    ],
    list_to_binary(DataList).
