%%%===================================================================
%%% Generated by generate_record.rake 2014-03-10 13:41:56 +0800
%%%===================================================================

-module(model_mapping).
-export([load/0]).
-include("include/db_schema.hrl").

load() ->
    record_mapper:add_mapping({config_items, record_info(fields, config_items)}),
    record_mapper:add_mapping({config_players, record_info(fields, config_players)}),
    record_mapper:add_mapping({config_stores, record_info(fields, config_stores)}),
    record_mapper:add_mapping({towns, record_info(fields, towns)}),
    record_mapper:add_mapping({users, record_info(fields, users)}).
