%%%===================================================================
%%% Generated by generate_record.rake 2014-01-29 00:41:20 +0800
%%%===================================================================

-module(model_mapping).
-export([load/0]).
-include("include/db_schema.hrl").

load() ->
    record_mapper:add_mapping({config_items, record_info(fields, config_items)}),
    record_mapper:add_mapping({towns, record_info(fields, towns)}),
    record_mapper:add_mapping({users, record_info(fields, users)}).
