%%%===================================================================
%%% Generated by generate_api.rb 2014-01-23 02:40:07 +0800
%%%===================================================================
-module(request_decoder).
-export(decode/2).

map([], [], Result) ->
    Result;
map([Key|Keys], [Value|Values], Result) ->
    map(Keys, Values, [{Key, Value}|Result]).

  
decode(Bin, 1) ->
    Keys = [udid],
    Rule = {string},
    Values = utils_protocol:decode(Bin, Rule),
    map(Keys, tuple_to_list(Values), []);
    
decode(Bin, 2) ->
    Keys = [user_id],
    Rule = {string},
    Values = utils_protocol:decode(Bin, Rule),
    map(Keys, tuple_to_list(Values), []).
    