%%%===================================================================
%%% Generated by generate_api.rb 2014-02-28 17:00:37 +0800
%%%===================================================================
-module(response_decoder).
-export([decode/1]).
-include("include/protocol.hrl").
  
decode(<<1:?SHORT, Bin0>>) ->
    {Name, Bin1} = utils_protocol:decode_string(Bin0),
    {PositionX, Bin2} = utils_protocol:decode_integer(Bin1),
    {PositionY, Bin3} = utils_protocol:decode_integer(Bin2),
    {UserId, Bin4} = utils_protocol:decode_string(Bin3),
    {[{name, Name}, {position_x, PositionX}, {position_y, PositionY}, {user_id, UserId}], Bin4};
decode(<<2:?SHORT, Bin0>>) ->
    {Name, Bin1} = utils_protocol:decode_string(Bin0),
    {Age, Bin2} = utils_protocol:decode_integer(Bin1),
    {Towns, Bin3} = utils_protocol:decode_array(Bin2, fun(Data) -> response_decoder:decode(Data) end),
    {[{name, Name}, {age, Age}, {towns, Towns}], Bin3}.