%%%===================================================================
%%% Generated by generate_api.rb 2014-02-28 18:08:05 +0800
%%%===================================================================
-module(response_encoder).
-export([encode/2]).
  
encode(town, Value) ->
    Type = 1,
    {Name, PositionX, PositionY, UserId} = Value,
    DataList = [
        utils_protocol:encode_short(Type),
        utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(PositionX),
        utils_protocol:encode_integer(PositionY),
        utils_protocol:encode_string(UserId)
    ],
    list_to_binary(DataList);
encode(building, Value) ->
    Type = 2,
    {Name, Position} = Value,
    DataList = [
        utils_protocol:encode_short(Type),
        utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(Position)
    ],
    list_to_binary(DataList);
encode(user, Value) ->
    Type = 3,
    {Uuid, Udid, Name, Gem, Paid, Building, Towns} = Value,
    DataList = [
        utils_protocol:encode_short(Type),
        utils_protocol:encode_string(Uuid),
        utils_protocol:encode_string(Udid),
        utils_protocol:encode_string(Name),
        utils_protocol:encode_integer(Gem),
        utils_protocol:encode_float(Paid),
        encode(building, Building),
        utils_protocol:encode_array(Towns, fun(Item) -> response_encoder:encode(town, Item) end)
    ],
    list_to_binary(DataList).