%%%===================================================================
%%% Generated by generate_api.rb 2014-03-10 17:56:05 +0800
%%%===================================================================
-module(routes).
-export([route/1]).

route(8) ->
    {sessions_controller, login};
route(9) ->
    {users_controller, public_info};
route(10) ->
    {heros_controller, info};
route(11) ->
    {heros_controller, infos};
route(12) ->
    {formations_controller, info};
route(13) ->
    {formations_controller, update}.
