%%%===================================================================
%%% Generated by generate_api.rb 2014-02-27 16:02:52 +0800
%%%===================================================================
-module(routes).
-export([route/1]).
  
route(1) ->
    {sessions_controller, login};
route(2) ->
    {users_controller, public_info}.