%%%===================================================================
%%% Generated by generate_api.rb 2014-07-28 16:06:37 +0800
%%%===================================================================
-module(api_encoder).
-export([encode/2, encode_protocol/2]).

encode(ProtocolName, Value) ->
    ProtocolId = api_protocol:protocol_id(ProtocolName),
    EncodedValue = encode_protocol(ProtocolName, Value),
    list_to_binary([utils_protocol:encode_short(ProtocolId), EncodedValue]).
encode_protocol(ok, Value) ->
    {Code} = Value,
    DataList = [
    utils_protocol:encode_integer(Code)
    ],
    list_to_binary(DataList);
encode_protocol(fail, Value) ->
    {Code, Desc} = Value,
    DataList = [
    utils_protocol:encode_integer(Code),
        utils_protocol:encode_string(Desc)
    ],
    list_to_binary(DataList);
encode_protocol(delete, Value) ->
    {TargetName, TargetUuid} = Value,
    DataList = [
    utils_protocol:encode_string(TargetName),
        utils_protocol:encode_string(TargetUuid)
    ],
    list_to_binary(DataList);
encode_protocol(delete_all, Value) ->
    {TargetName} = Value,
    DataList = [
    utils_protocol:encode_string(TargetName)
    ],
    list_to_binary(DataList);
encode_protocol(user, Value) ->
    {Uuid, Udid, Name} = Value,
    DataList = [
    utils_protocol:encode_string(Uuid),
        utils_protocol:encode_string(Udid),
        utils_protocol:encode_string(Name)
    ],
    list_to_binary(DataList);
encode_protocol(login_params, Value) ->
    {Udid} = Value,
    DataList = [
    utils_protocol:encode_string(Udid)
    ],
    list_to_binary(DataList).
