%%%===================================================================
%%% Generated by generate_api.rb 2014-07-28 16:06:37 +0800
%%%===================================================================
-module(api_protocol).
-export([protocol_id/1, protocol_name/1]).

-define(NAME_MAPPED, [{ok, 0},
                      {fail, 1},
                      {delete, 2},
                      {delete_all, 3},
                      {user, 4},
                      {login_params, 5}]).

-define(ID_MAPPED, [{0, ok},
                    {1, fail},
                    {2, delete},
                    {3, delete_all},
                    {4, user},
                    {5, login_params}]).

protocol_id(Name) -> 
    proplists:get_value(Name, ?NAME_MAPPED).

protocol_name(Id) -> 
    proplists:get_value(Id, ?ID_MAPPED).
