%%%===================================================================
%%% Generated by generate_record.rake 2014-07-28 16:06:37 +0800
%%%===================================================================

-module(model_mapping).
-export([load/0]).
-include("include/db_schema.hrl").

load() ->
    record_mapper:add_mapping({config_error_msgs, record_info(fields, config_error_msgs)}),
    record_mapper:add_mapping({config_item_names, record_info(fields, config_item_names)}),
    record_mapper:add_mapping({config_pushes, record_info(fields, config_pushes)}),
    record_mapper:add_mapping({config_quests, record_info(fields, config_quests)}),
    record_mapper:add_mapping({config_system_messages, record_info(fields, config_system_messages)}),
    record_mapper:add_mapping({users, record_info(fields, users)}).
