%%%===================================================================
%%% Generated by generate_api.rb 2014-07-28 16:06:37 +0800
%%%===================================================================
-module(routes).
-export([route/1]).

route(5) ->
    {sessions_controller, login};
route(UnmatchedProtocol) ->
    Msg = list_to_binary(io_lib:format("Request Protocol[~p] Not Found!", [UnmatchedProtocol])),
    {error, Msg}.
