%%% Generated by generate_config.rake 2014-03-11 11:39:44 +0800
-define(CONFIG_MODELS, [
        config_users,
        config_stores,
        config_items,
        config_players,
        config_player_grows
        ]).
