%%%===================================================================
%%% Generated by generate_record.rake 
%%%===================================================================

-define(DB_DEVELOPMENT, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_development'}, {pool, 5}, {username, 'root'}, {password, ''}]).
-define(DB_TEST, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_development'}, {pool, 5}, {username, 'root'}, {password, ''}]).
-define(DB_PRODUCTION, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_production'}, {pool, 5}, {username, 'root'}, {password, ''}]).
