%%%===================================================================
%%% Generated by generate_record.rake 2014-03-11 11:35:38 +0800
%%%===================================================================

-define(DB_DEVELOPMENT, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_production'}, {pool, 5}, {username, 'root'}, {password, ''}]).
-define(DB_TEST, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_test'}, {pool, 5}, {username, 'root'}, {password, ''}]).
-define(DB_CONFIG, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_config'}, {pool, 5}, {username, 'root'}, {password, ''}]).
-define(DB_PRODUCTION, [{adapter, 'mysql2'}, {encoding, 'utf8'}, {reconnect, 0}, {database, 'game_server_production'}, {pool, 5}, {username, 'root'}, {password, ''}]).
