%%%===================================================================
%%% Generated by generate_record.rake 2014-03-07 10:38:59 +0800
%%%===================================================================

-record(config_items, {
        id,
        title,
        ver,
        obj,
        number,
        no,
        url,
        pc,
        ken}).

-record(towns, {
        uuid,
        user_id,
        name,
        x,
        y,
        created_at,
        updated_at}).

-record(users, {
        uuid,
        udid,
        name,
        gem,
        paid,
        created_at,
        updated_at}).

