%%%===================================================================
%%% Generated by generate_record.rake 2014-01-21 15:34:01 +0800
%%%===================================================================

-record(towns, {
        uuid,
        user_id,
        name,
        x,
        y,
        created_at,
        updated_at}).

-record(users, {
        uuid,
        name,
        gem,
        paid,
        created_at,
        updated_at}).

