%%%===================================================================
%%% Generated by generate_record.rake 
%%%===================================================================

-define(DB_TABLE_NAMES, [
    alliances,
    alliance_activity_unlocks,
    alliance_applications,
    alliance_auctions,
    alliance_bosses,
    alliance_helps,
    alliance_researches,
    alliance_shop_items,
    contest_records,
    copies,
    equips,
    formations,
    gem_slots,
    gemstones,
    grids,
    heros,
    items,
    letters,
    messages,
    player_summaries,
    quests,
    quest_summaries,
    server_events,
    server_notices,
    towns,
    users,
    user_letters,
    wanteds
]).
