%%% Generated by generate_config.rake 
-record(translate_menus, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_npcs, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_guilds, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_skills, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_waypoints, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_quests, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_stories, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_items, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

-record(translate_alerts, {
        en,
        cn,
        kr,
        jp,
        zh,
        fr,
        ger,
        ru,
        sp,
        it,
        po}).

