%%% Generated by generate_config.rake 
-define(TRANSLATE_DATA_NAMES, [
    translate_menus,
    translate_npcs,
    translate_guilds,
    translate_skills,
    translate_waypoints,
    translate_quests,
    translate_stories,
    translate_items,
    translate_alerts
]).
